apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fgnh1fcgp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fgnh1fcgp-nodejs 
  name: fgnh1fcgp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fgnh1fcgp-nodejs 
