apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fgnh1fcgp-nodejs 
  janus-idp.io/tekton: fgnh1fcgp-nodejs
  backstage.io/kubernetes-id: fgnh1fcgp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fgnh1fcgp-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml